apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  output:
    image: 'image-registry.openshift-image-registry.svc.cluster.local:5000/pang/pong:latest'
  retention:
    failedLimit: 5
    succeededLimit: 3
    ttlAfterFailed: 15m
    ttlAfterSucceeded: 30m
  source:
    git:
      url: 'https://github.com/agbaroni/pong'
    type: Git
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
