apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"pong:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"pong\")].image"}]'
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - image: pong:latest
          imagePullPolicy: Always
          name: {{ .Values.name }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 8
            timeoutSeconds: 2
