apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: pang
spec:
  replicas: 1
  selector:
    app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - image: pong:latest
          imagePullPolicy: Always
          name: pong
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 8
            timeoutSeconds: 2
