apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: pang
spec:
  replicas: 1
  selector:
    app: {{ .Values.app_name }}
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - image: {{ .Values.app_name }}:{{ .Values.app_version }}
          imagePullPolicy: Always
          name: {{ .Values.app_name }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 8
            timeoutSeconds: 2
