apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      importPolicy:
        insecure: true
      referencePolicy:
        type: Source
