apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pong
  namespace: pang
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      importPolicy:
        insecure: true
      referencePolicy:
        type: Source
