apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pong
  namespace: pang
spec:
  to:
    kind: Service
    name: pong
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
